import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { Container } from "@/components/Container";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PokéMart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen bg-zinc-100`} >
        <Container>
        <Header/>
        {children}
        <Footer/>
        </Container>
        </body>
    </html>
  );
}
